/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.Universo;
import com.sun.j3d.utils.universe.SimpleUniverse;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.GraphicsConfiguration;
import java.awt.Rectangle;
import javax.media.j3d.Canvas3D;
import javax.swing.JFrame;
import javax.swing.JLabel;
import sun.java2d.SunGraphicsEnvironment;

/**
 *
 * @author rafae
 */
public class GameView extends javax.swing.JFrame {

    /**
     * Creates new form GameView
     */
    Canvas3D canvas2;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
    
    private Universo universe;
    
    public GameView() {
        initComponents();
        score.setVisible(true);
        points.setVisible(true);
        //points.setBackground(new Color(0, 255, 0, 0));
        //points.setOpaque(false);
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setState(JFrame.MAXIMIZED_BOTH);
        
        
        Canvas3D canvas = new Canvas3D(SimpleUniverse.getPreferredConfiguration());
        canvas.setSize(1000,700);

        // Se crea el Universo con dicho Canvas3D
        this.universe = new Universo (canvas);
        
        this.canvas2 = canvas;
        
        Container contentPane = this.getContentPane();
        contentPane.setLayout(new BorderLayout());
        contentPane.add(canvas2, BorderLayout.CENTER);

        
        pack();
        
        
    }

    public void showWindow () {
        setVisible (true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        play = new javax.swing.JButton();
        points = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        camara_nave = new javax.swing.JButton();
        camara_general = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        play.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        play.setText("Play");
        play.setBorderPainted(false);
        play.setContentAreaFilled(false);
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        points.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        points.setText("Points");

        score.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 48)); // NOI18N
        score.setForeground(new java.awt.Color(255, 51, 51));
        score.setText("10");

        camara_nave.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        camara_nave.setText("Cámara Nave");
        camara_nave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camara_naveActionPerformed(evt);
            }
        });

        camara_general.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        camara_general.setText("Cámara General");
        camara_general.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camara_generalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(camara_general)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1063, Short.MAX_VALUE)
                        .addComponent(points)
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(camara_nave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(score)
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(points)
                    .addComponent(play))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(camara_nave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(score))
                .addGap(29, 29, 29)
                .addComponent(camara_general, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed

        
        score.setVisible(true);
        points.setVisible(true);
    }//GEN-LAST:event_playActionPerformed

    private void camara_naveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camara_naveActionPerformed
        universe.camaraNave();
    }//GEN-LAST:event_camara_naveActionPerformed

    private void camara_generalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camara_generalActionPerformed
        // TODO add your handling code here:
        universe.camaraPerspectiva();
    }//GEN-LAST:event_camara_generalActionPerformed

    
    public void setScore(int puntos)
    {
        String num = Integer.toString(puntos);
        
        this.score.setText(num);
        this.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton camara_general;
    private javax.swing.JButton camara_nave;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JButton play;
    private javax.swing.JLabel points;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
